{"uuid": "2b5e5d5c-54ce-40a7-a3dc-f394cf779fff", "children": ["f97f1966-4587-4f82-98bd-3cb2579ae30c"], "befores": [{"name": "Conftest", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'read'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/liuchengxu/work/sunxing/sunxing/TestSuite/CcsUserLoginController/conftest.py\", line 23, in Conftest\n    response_list=json.load(response.json())\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py\", line 293, in load\n    return loads(fp.read(),\n"}, "start": 1582547041504, "stop": 1582547041548}], "start": 1582547041504, "stop": 1582547041615}