{"uuid": "d026af69-0a92-49fa-8f59-78883402bd94", "children": ["f5e02921-3fc8-4743-9a64-0b3b394d2cc6"], "befores": [{"name": "Conftest", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'int' is not iterable\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 783, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/liuchengxu/work/sunxing/sunxing/TestSuite/CcsUserLoginController/conftest.py\", line 26, in Conftest\n    if   response in 200:\n"}, "start": 1582547785638, "stop": 1582547785688}], "start": 1582547785638, "stop": 1582547785743}